### ISSUE TITLE
problem to run docker-compose

### ISSUE THREAD

**Issue by EduardoAraujoB** [weslenng/chest#1]
I try to run your repository and recieved an error from docker compose
![docker compose problem](https://user-images.githubusercontent.com/42449213/81210900-f1aac600-8fa8-11ea-9b5e-a93d56aeb07f.png)

**Comment by EduardoAraujoB** [comment]
ops, I solve this usin the 3.7 version of docker compose instead of 3.8 on docker file

**Comment by weslenng** [comment]
@EduardoAraujoB Try again
